In [23]:
import numpy as np
import pandas as pd
import io
from IPython.display import clear_output
clear_output()

## Carga del dataset

In [24]:
### Para cargar el archivo desde la PC
'''
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['student_habits_performance.csv']))
df.head()
'''

"\nfrom google.colab import files\nuploaded = files.upload()\ndf = pd.read_csv(io.BytesIO(uploaded['student_habits_performance.csv']))\ndf.head()\n"

In [25]:
### Si el archivo ya est√° en el entorno Colab, modificar path
df = pd.read_csv('/content/sample_data/student_habits_performance.csv')
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

## Descripci√≥n del dataset

In [26]:
df.describe()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,84.131700,6.470100,3.042000,5.438000,69.601500
std,2.3081,1.46889,1.172422,1.075118,9.399246,1.226377,2.025423,2.847501,16.888564
min,17.0000,0.00000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.7500,2.60000,1.700000,1.000000,78.000000,5.600000,1.000000,3.000000,58.475000
50%,20.0000,3.50000,2.500000,1.800000,84.400000,6.500000,3.000000,5.000000,70.500000
75%,23.0000,4.50000,3.300000,2.525000,91.025000,7.300000,5.000000,8.000000,81.325000
max,24.0000,8.30000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

In [27]:
df.size

16000

In [28]:
df.shape

(1000, 16)

In [29]:
df.dtypes

student_id                        object
age                                int64
gender                            object
study_hours_per_day              float64
social_media_hours               float64
netflix_hours                    float64
part_time_job                     object
attendance_percentage            float64
sleep_hours                      float64
diet_quality                      object
exercise_frequency                 int64
parental_education_level          object
internet_quality                  object
mental_health_rating               int64
extracurricular_participation     object
exam_score                       float64
dtype: object

In [30]:
print(df.info)

<bound method DataFrame.info of     student_id  age  gender  study_hours_per_day  social_media_hours  \
0        S1000   23  Female                  0.0                 1.2
1        S1001   20  Female                  6.9                 2.8
2        S1002   21    Male                  1.4                 3.1
3        S1003   23  Female                  1.0                 3.9
4        S1004   19  Female                  5.0                 4.4
..         ...  ...     ...                  ...                 ...
995      S1995   21  Female                  2.6                 0.5
996      S1996   17  Female                  2.9                 1.0
997      S1997   20    Male                  3.0                 2.6
998      S1998   24    Male                  5.4                 4.1
999      S1999   19  Female                  4.3                 2.9

     netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0              1.1            No                   85.0          8.0
1              2.3            No                   97.3          4.6
2              1.3            No                   94.8          8.0
3              1.0            No                   71.0          9.2
4              0.5            No                   90.9          4.9
..             ...           ...                    ...          ...
995            1.6            No                   77.0          7.5
996            2.4           Yes                   86.0          6.8
997            1.3            No                   61.9          6.5
998            1.1           Yes                  100.0          7.6
999            1.9            No                   89.4          7.1

    diet_quality  exercise_frequency parental_education_level  \
0           Fair                   6                   Master
1           Good                   6              High School
2           Poor                   1              High School
3           Poor                   4                   Master
4           Fair                   3                   Master
..           ...                 ...                      ...
995         Fair                   2              High School
996         Poor                   1              High School
997         Good                   5                 Bachelor
998         Fair                   0                 Bachelor
999         Good                   2                 Bachelor

    internet_quality  mental_health_rating extracurricular_participation  \
0            Average                     8                           Yes
1            Average                     8                            No
2               Poor                     1                            No
3               Good                     1                           Yes
4               Good                     1                            No
..               ...                   ...                           ...
995             Good                     6                           Yes
996          Average                     6                           Yes
997             Good                     9                           Yes
998          Average                     1                            No
999          Average                     8                            No

     exam_score
0          56.2
1         100.0
2          34.3
3          26.8
4          66.4
..          ...
995        76.1
996        65.9
997        64.4
998        69.7
999        74.9

[1000 rows x 16 columns]>

##**EDA**

In [31]:
# vemos si contiene valores duplicados
duplicados = df[df.duplicated()]
print('Filas duplicadas excluyendo la primera aparici√≥n:')
print(duplicados)

Filas duplicadas excluyendo la primera aparici√≥n:
Empty DataFrame
Columns: [student_id, age, gender, study_hours_per_day, social_media_hours, netflix_hours, part_time_job, attendance_percentage, sleep_hours, diet_quality, exercise_frequency, parental_education_level, internet_quality, mental_health_rating, extracurricular_participation, exam_score]
Index: []

### No encontramos duplicados. Buscamos valores nulos

In [32]:
df.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [33]:
# Extraemos los Nan de la serie 'parental_education_level' por su indice
indices_nan = df[df['parental_education_level'].isna()].index

# como tenemos una lista de indices que tienen los nan de ''parental_education_level''
df.loc[indices_nan,'parental_education_level'] = np.random.choice(
    ['High School','Bachelor'],
    size = len(indices_nan),
    p = [0.392/0.742, 0.35/0.742]
) # esto agarra de la serie parental_education_level los indices que tienen Nan,
  # y le asigna aleatoriamente con np.random.choice el valor High school o Bachelor
  #size = len(indices_nan) hace q genere tantos valores aleatorios como tengo en indices nan (91)
  # p = .... como del total 0,742 es lo q representan los valores bimodales de este total saco el porcentaje
  # entonces me da la probabilidad proporcional a cada categoria segun su distribucion real. es la proporcion real digamos.

In [34]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [35]:
df.head(10)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,Fair,1,Master,Average,4,No,100.0
6,S1006,21,Female,5.6,1.5,1.4,Yes,85.8,6.5,Good,2,Master,Poor,4,No,89.8
7,S1007,21,Female,4.3,1.0,2.0,Yes,77.7,4.6,Fair,0,Bachelor,Average,8,No,72.6
8,S1008,23,Female,4.4,2.2,1.7,No,100.0,7.1,Good,3,Bachelor,Good,1,No,78.9
9,S1009,18,Female,4.8,3.1,1.3,No,95.4,7.5,Good,5,Bachelor,Good,10,Yes,100.0